version: '1'
services:
  eureka-server:
    image: eureka-server:1.0
    ports:
      - "8761:8761"
  config-service:
    image: config-service:1.0
    ports:
      - "8084:8084"

networks:
  common-network:
    driver: bridge